---
comments: false
---

# Contributing

If you want to improve, extend, or experiment with this publication or its underlying analysis, you'll find useful information in this document.

## Source Code

All the code necessary to reproduce this publication is hosted on GitHub at [this URL](FIXME).

## Installation

::: {.callout-note}
The publication is rendered with [Quarto](https://quarto.org/). If you don't have it installed (check with `quarto --version`), you can install it [here](https://quarto.org/docs/get-started/).
:::

This repository uses conda to manage the computational and build environment. If you don't have it installed (check with `conda --version`), you can find operating system-specific instructions for installing miniconda [here](https://docs.conda.io/projects/miniconda/en/latest/). After installing, run the following commands to create and activate the environment.

```bash
conda env create -n [ENV-NAME] --file env.yml
conda activate [ENV-NAME]
```

Now, install any internal packages in the repository:

```bash
pip install -e .
```

And finally, if you plan to submit a pull request, install the [pre-commit](https://pre-commit.com/) hooks:

```bash
pre-commit install
```

## Reproduce

The analysis, and therefore the publication itself, can be reproduced with the following command:

```bash
make execute
```

This will generate the directory `_site/`. Open `_site/index.html` to view your local copy of the publication.

## Modify

To modify or extend any analyses, open up `index.ipynb` with Jupyter or your favorite IDE:

```bash
jupyter-lab index.ipynb
```

## Preview

To create a live preview of your pub, run the following:

```bash
make preview
```

This will open a local copy of the publication in your default browser. The command watches for changes such that whenever `index.ipynb` is saved, the publication is re-rendered.

## Publish a Revision

Publishing is handled automatically with a GitHub Action that triggers whenever a pull request is merged into the `main` branch. So once you're happy with your changes, please open a pull request for us to review. Once the changes are approved and the pull request is merged, your changes will be live.

Before opening a pull request, there's a few required tasks.

1. Add yourself to the authors list in the front matter of `index.ipynb`.
2. execute the notebook locally using `make execute`. This command will update `index.ipynb` with the latest execution results. Importantly, it will also generate any runtime artifacts in the `_freeze/` directory. Commit `index.ipynb` and all files in the `_freeze/` directory.

After this, feel free to open a pull request. We look forward to collaborating with you.
